# Generated by Django 4.0.3 on 2022-04-03 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filebox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(max_length=255, verbose_name='Tipo')),
                ('message', models.CharField(max_length=255, null=True, verbose_name='Message')),
                ('file', models.CharField(max_length=255, null=True, verbose_name='File')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('partial', models.IntegerField(default=0, verbose_name='Parcial')),
                ('error', models.TextField(null=True, verbose_name='Erro')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Início')),
                ('end', models.DateTimeField(null=True, verbose_name='Fim')),
                ('notify', models.BooleanField(default=False)),
                ('url', models.CharField(default='', max_length=524, verbose_name='Redirect URL')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
